# Generated by Django 2.2.1 on 2019-10-08 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userlogin'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtaker',
            name='matric_no',
        ),
        migrations.AddField(
            model_name='classtaker',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
