# Generated by Django 2.2.1 on 2019-10-08 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191008_1206'),
        ('course', '0002_auto_20191008_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.User')),
            ],
        ),
        migrations.AlterModelOptions(
            name='courseindex',
            options={'verbose_name_plural': 'Course Indexes'},
        ),
        migrations.RenameField(
            model_name='class',
            old_name='index_type',
            new_name='course_index_type',
        ),
        migrations.RenameField(
            model_name='classtaker',
            old_name='index',
            new_name='course_index',
        ),
        migrations.RenameField(
            model_name='courseindextype',
            old_name='index',
            new_name='course_index',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='matric_no',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.User'),
        ),
        migrations.AlterField(
            model_name='classtaker',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.User'),
        ),
        migrations.DeleteModel(
            name='ClassInstructor',
        ),
    ]
