# Generated by Django 2.2.1 on 2019-10-09 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191008_1206'),
        ('course', '0003_auto_20191008_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseIndex')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.User')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseInstructor',
        ),
    ]
