# Generated by Django 2.2.1 on 2019-10-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20191009_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_time',
            field=models.TimeField(blank=True, null=True, verbose_name='attendance time'),
        ),
    ]
