# Generated by Django 2.2.1 on 2019-10-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(choices=[('student', 'student'), ('staff', 'staff')], max_length=20)),
                ('face_image', models.ImageField(upload_to='face_images/')),
                ('sign_image', models.ImageField(upload_to='sign_images/')),
            ],
        ),
    ]
