# Generated by Django 2.2.1 on 2019-10-07 07:49

from django.db import migrations, models
import functools
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face_image',
            field=models.ImageField(upload_to=functools.partial(login.models._update_filename, *(), **{'path': 'face_images/'})),
        ),
        migrations.AlterField(
            model_name='user',
            name='sign_image',
            field=models.ImageField(upload_to=functools.partial(login.models._update_filename, *(), **{'path': 'sign_images/'})),
        ),
    ]
