# Generated by Django 2.2.1 on 2019-10-07 08:45

from django.db import migrations, models
import functools
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20191007_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sign_image',
            field=models.ImageField(blank=True, upload_to=functools.partial(login.models._update_filename, *(), **{'path': 'sign_images/'})),
        ),
    ]
